# Generated by Django 4.0.3 on 2022-04-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TYPE', models.CharField(choices=[('OS', 'Oneshot'), ('CL', 'Class'), ('CA', 'Campaign'), ('MO', 'Monster')], default='OS', max_length=2)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
            ],
        ),
    ]
